# Generated by Django 4.2.6 on 2023-10-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='star',
        ),
    ]
