# Generated by Django 4.2.6 on 2023-10-29 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_products_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_name', models.CharField(max_length=150)),
                ('cost', models.IntegerField(default=1)),
                ('product1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product1', to='main.products')),
                ('product2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product2', to='main.products')),
                ('product3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product3', to='main.products')),
                ('product4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product4', to='main.products')),
            ],
        ),
    ]
