# Generated by Django 4.2.7 on 2023-11-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_blogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AddField(
            model_name='blogs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
